#!/usr/bin/python
import sys
import subprocess
import re
from optparse import OptionParser

FILE_PATTERN = "^.*/db/migrations/[0-9+].*\.rb$"
SKIP_KEYWORD = "skip-migration-check"
SVNLOOK = "svnlook"

def check_filenames(look_command):
  if should_skip_check_for_commit(look_command):
    return 0
  error = 0
  added_filenames = get_files_added_in_commit(look_command)
  for added_filename in added_filenames:
    if is_migration_file(added_filename):
      last_existing_file = get_last_existing_file_after(added_filename, added_filenames, look_command)
      if last_existing_file:
        sys.stderr.write("Error: The added file \"%s\" must have a filename \
alphabetically after the existing \"%s\".\n" % (added_filename, last_existing_file))
        error += 1
  if error > 0:
    output_ignore_message()
  return error

def should_skip_check_for_commit(look_command):
  return SKIP_KEYWORD in " ".join(get_commit_message(look_command)).split(" ")

def output_ignore_message():
  sys.stderr.write("If you want to commit this anyway, include \"%s\" in the commit message.\n" % SKIP_KEYWORD)

def is_migration_file(filename):
  return bool(re.match(FILE_PATTERN, filename))

def get_migration_dir(filename):
  return filename[0:filename.rfind("/") + 1]

def get_files_added_in_commit(look_command):
  def added(line):
    return line and line[0] == "A"
  def filename(line):
    return line[4:]
  return [filename(line) for line in get_changed_files(look_command) if added(line)]

def get_last_existing_file_after(filename, added_filenames, look_command):
  existing_files = get_existing_files_in(get_migration_dir(filename), added_filenames, look_command)
  existing_migrations = [f for f in existing_files if is_migration_file(f)]
  existing_migrations.sort()
  if existing_migrations and filename < existing_migrations[-1]:
    return existing_migrations[-1]
  return None

def get_existing_files_in(path, added_filenames, look_command):
  all_files = command_output("%s %s" % (look_command % "tree --full-paths", path))
  return [filename for filename in all_files if filename not in added_filenames]
  
def get_changed_files(look_command):
  return command_output(look_command % "changed")

def get_commit_message(look_command):
  return command_output(look_command % "log")

def command_output(cmd):
  "Captures a command's standard output."
  return subprocess.Popen(cmd.split(), stdout=subprocess.PIPE).communicate()[0].split("\n")

def main():
  usage = """Usage: %prog REPO TXN

Run pre-commit verification on a repository transaction."""
  parser = OptionParser(usage=usage)
  parser.add_option("-r", "--revision",
                    help="Test mode. Specify a revision instead of a transaction.",
                    action="store_true", default=False)

  try:
    (options, (repos, transaction_or_revision)) = parser.parse_args()
    look_option = ("--transaction", "--revision")[options.revision]
    look_command = "%s %s %s %s %s" % (SVNLOOK, "%s", repos, look_option, transaction_or_revision)
    return check_filenames(look_command)
  except:
    parser.print_help()
    return 1

if __name__ == "__main__":
  sys.exit(main())